# Generated by Django 4.1.3 on 2022-12-08 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('user', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=25)),
            ],
        ),
        migrations.RenameField(
            model_name='room',
            old_name='user',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='value',
        ),
    ]
